[ERROR] 2017-05-25 05:06:43,562 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-25 05:10:44,413 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-25 05:10:44,415 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:38:51,757 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:38:51,769 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:42:52,688 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:42:52,689 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:46:53,386 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:46:53,387 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:50:54,326 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:50:54,328 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:54:55,044 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:54:55,045 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 02:58:55,594 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 02:58:55,596 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:02:56,257 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:02:56,259 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:06:57,242 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:06:57,243 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:10:58,378 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:10:58,380 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:15:17,109 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:15:17,113 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:19:30,061 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:19:30,066 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:23:44,066 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:23:44,070 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:27:56,072 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:27:56,075 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:32:10,084 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:32:10,087 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:36:24,073 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:36:24,076 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:40:38,071 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:40:38,074 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:44:51,119 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:44:51,122 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:49:05,083 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:49:05,086 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:53:19,129 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:53:19,130 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 03:57:32,074 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 03:57:32,077 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:01:32,982 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:01:32,983 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:05:33,854 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:05:33,856 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:09:34,620 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:09:34,621 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:13:34,677 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:13:34,679 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:17:35,550 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:17:35,551 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:21:36,268 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:21:36,269 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:25:37,055 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:25:37,056 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:29:37,886 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:29:37,888 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:33:38,020 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:33:38,022 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:37:38,952 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:37:38,954 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:41:39,705 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:41:39,708 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 04:49:59,945 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:49:59,951 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[ERROR] 2017-05-26 04:53:09,362 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmed \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khans\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:53:00.512Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named includes.sample
[ERROR] 2017-05-26 04:53:57,757 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmed s\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:53:46.654Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named includes.sample
[ERROR] 2017-05-26 04:53:57,910 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 04:53:57.758292-127.0.0.1-5cc
[ERROR] 2017-05-26 04:54:35,287 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmed\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:53:46.654Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named includes.sample
[ERROR] 2017-05-26 04:54:35,294 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 04:54:35.288043-127.0.0.1-1b7
[DEBUG] 2017-05-26 04:55:36,757 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 04:55:36,761 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[ERROR] 2017-05-26 04:56:27,321 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmed \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khans\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:53:00.512Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named includes.sample
[ERROR] 2017-05-26 04:56:27,596 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 04:56:27.323056-127.0.0.1-30d
[ERROR] 2017-05-26 04:58:13,028 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmed \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:58:06.927Z\"}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named includes.sample
[ERROR] 2017-05-26 04:58:13,183 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 04:58:13.029388-127.0.0.1-cbe
[DEBUG] 2017-05-26 05:01:52,487 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:01:52,493 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[ERROR] 2017-05-26 05:06:10,085 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmeds\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:58:06.927Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named news.includes.sample
[ERROR] 2017-05-26 05:06:10,216 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:06:10.086774-127.0.0.1-56d
[DEBUG] 2017-05-26 05:09:55,619 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:09:55,623 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:13:56,275 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:13:56,277 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[ERROR] 2017-05-26 05:13:59,516 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmeds\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:58:06.927Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named news.includes.sample
[ERROR] 2017-05-26 05:13:59,523 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:13:59.517357-127.0.0.1-244
[DEBUG] 2017-05-26 05:17:56,964 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:17:56,966 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:21:57,726 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:23:09,524 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:23:09.517804-127.0.0.1-d0d
