[ERROR] 2017-05-26 05:23:09,516 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedasda \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:23:02.645Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named news.includes.sample
[ERROR] 2017-05-26 05:28:53,854 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedsaa\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T11:58:06.927Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes no arguments (2 given)
[ERROR] 2017-05-26 05:28:54,002 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:28:53.854812-127.0.0.1-8f2
[ERROR] 2017-05-26 05:29:49,143 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedss \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:29:42.823Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes exactly 1 argument (2 given)
[ERROR] 2017-05-26 05:29:49,337 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:29:49.144570-127.0.0.1-0e4
[ERROR] 2017-05-26 05:31:47,619 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedasd \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:31:38.342Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    hooks.append(frappe.get_attr(handler))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/sample_application/sample_application/sample.py", line 1
    def changes( self ):
    ^
IndentationError: unexpected indent
[ERROR] 2017-05-26 05:31:47,759 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:31:47.620844-127.0.0.1-905
[ERROR] 2017-05-26 05:32:28,429 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedss\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:32:10.257Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes exactly 1 argument (2 given)
[ERROR] 2017-05-26 05:32:40,305 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedss\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:32:10.257Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes exactly 1 argument (2 given)
[ERROR] 2017-05-26 05:32:41,445 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:32:40.326193-127.0.0.1-543
[ERROR] 2017-05-26 05:33:10,787 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmeds \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:33:03.800Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes exactly 1 argument (2 given)
[ERROR] 2017-05-26 05:33:10,915 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:33:10.788113-127.0.0.1-00c
[DEBUG] 2017-05-26 05:33:24,412 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:33:24,420 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[ERROR] 2017-05-26 05:33:44,651 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedsss \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:33:36.478Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes no arguments (2 given)
[ERROR] 2017-05-26 05:33:44,795 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:33:44.652126-127.0.0.1-6aa
[ERROR] 2017-05-26 05:34:02,286 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py:
Site: site.local-development
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"user_image\":\"\",\"last_name\":\"Saboor\",\"simultaneous_sessions\":1,\"creation\":\"2017-05-26 16:43:29.408805\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"roles\":[],\"full_name\":\"Ahmed  Saboor\",\"owner\":\"Administrator\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Buying\",\"Communication\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Customer\",\"Desk\",\"Employee\",\"Fees\",\"File Manager\",\"HR\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Lead\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Ni Dark Theme\",\"Ni Light Theme\",\"POS\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Room\",\"Sales Invoice\",\"Sample Applications\",\"Schools\",\"Selling\",\"Setup\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"ToDo\",\"Warranty Claim\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ahmedsss \",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"\",\"idx\":0,\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"ahmed@riksof.com\",\"username\":\"ahmed_\",\"defaults\":[],\"user_type\":\"Website User\",\"user_emails\":[],\"doctype\":\"User\",\"middle_name\":\"Khan\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"ahmed@riksof.com\",\"language\":\"en-US\",\"reset_password_key\":\"a7V1qGkqYooq3peKxebjalKMhldJ9jg6\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2017-05-26 16:49:35.070612\",\"frappe_userid\":\"5f5fc57db0bc5aef3d1b6cf172ad79b44fc0d54\",\"__last_sync_on\":\"2017-05-26T12:33:36.478Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: changes() takes no arguments (2 given)
[ERROR] 2017-05-26 05:34:02,396 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-26 05:34:02.286876-127.0.0.1-e20
[DEBUG] 2017-05-26 05:37:25,328 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:37:25,331 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:42:02,159 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:42:02,163 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:46:03,199 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:46:03,201 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:50:04,130 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:50:04,132 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:54:05,049 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:54:05,051 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 05:58:05,472 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 05:58:05,474 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 06:02:06,275 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 06:02:06,276 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 06:06:06,717 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 06:06:06,719 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 06:10:07,702 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 06:10:07,704 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 06:14:08,673 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 06:14:08,675 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-26 06:18:09,350 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-26 06:18:09,352 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:32:02,467 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:32:02,475 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:36:03,236 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:36:03,238 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:40:04,257 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:40:04,259 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:44:05,379 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:44:05,381 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:48:17,064 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:48:17,066 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:52:17,334 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:52:17,335 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 20:56:18,041 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 20:56:18,044 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:00:18,547 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:00:18,549 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:07:04,636 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:07:04,639 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:11:05,387 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:11:05,389 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:15:06,205 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:15:06,207 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:19:07,069 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:19:07,071 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:23:08,035 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:23:08,037 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:27:09,067 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:27:09,069 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:31:09,985 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:31:09,987 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:35:10,770 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:35:10,772 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:39:11,619 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:39:11,621 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:43:47,770 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:43:47,774 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 21:51:57,293 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 21:51:57,296 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 22:10:51,192 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 22:10:51,196 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 22:14:51,844 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 22:14:51,846 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 22:23:00,926 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 22:23:00,930 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 22:27:01,706 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
[ERROR] 2017-05-29 22:27:01,708 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 63, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 207, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 554, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 107, in sql
    self.connect()
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/database.py", line 53, in connect
    use_unicode=True, charset='utf8mb4')
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/user/Documents/ERPNext-22-05-2017/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'localhost' (using password: YES)")

[DEBUG] 2017-05-29 22:38:03,784 | /Users/user/Documents/ERPNext-22-05-2017/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site.local-development
Queued events for site site.local-development
